### ISSUE TITLE
I am not able to use this with webpack

### ISSUE THREAD

**Issue by kishoresattu** [Kong/unirest-nodejs#97]
Webpack doesn't support node native modules like fs. Because of that I am not able to use this module in my project. Is there work around for that?

**Comment by nijikokun** [comment]
Currently there is no browser only version of Unirest

**Comment by edwardchanjw** [comment]
Direct copy from HN, https://news.ycombinator.com/item?id=6588963

Since it is built ontop of request, you could swap out the node library for this one: https://github.com/iriscouch/browser-request and it should work :)

Would require some maintenance to make it work though normally. Anyway good luck to Mashape, hopefully there is good business to keep funding to make it work.
